##############################################################
# Design Constraints (SDC 2.1)
# Design: {{TOP_MODULE}}
# Convention: {domain}_clk, i_/o_ port prefix per CLAUDE.md
# Generated by: constraint-writer
##############################################################

##############################################################
# 1. Clock Definitions
##############################################################
# Primary clocks — from requirements.json or timing_constraints.json
create_clock -period {{SYS_PERIOD_NS}} -name sys_clk [get_ports sys_clk]
# create_clock -period {{AXI_PERIOD_NS}} -name axi_clk [get_ports axi_clk]

# Generated clocks — from PLLs, clock dividers
# create_generated_clock -name fast_clk \
#   -source [get_ports sys_clk] \
#   -multiply_by 2 \
#   [get_pins u_pll/o_clk_out]

# create_generated_clock -name slow_clk \
#   -source [get_ports sys_clk] \
#   -divide_by 4 \
#   [get_pins u_clk_div/o_clk_div]

##############################################################
# 2. Clock Uncertainty & Transition
##############################################################
# Jitter (source) + skew (network) + margin
set_clock_uncertainty -setup 0.3 [get_clocks sys_clk]
set_clock_uncertainty -hold  0.1 [get_clocks sys_clk]

# Clock transition (slew) — technology dependent
set_clock_transition 0.15 [get_clocks sys_clk]

##############################################################
# 3. Clock Domain Relationships
##############################################################
# Asynchronous domains — no timing analysis between these
# set_clock_groups -asynchronous \
#   -group [get_clocks sys_clk] \
#   -group [get_clocks axi_clk]

# Synchronous but with phase shift
# set_clock_groups -physically_exclusive \
#   -group [get_clocks clk_0] \
#   -group [get_clocks clk_180]

##############################################################
# 4. Input Constraints
##############################################################
# External input delay relative to launching clock
# Max = Tclk_q(max) + Tboard(max), Min = Tclk_q(min) + Tboard(min)
set_input_delay -clock sys_clk -max {{INPUT_MAX_NS}} [get_ports i_data*]
set_input_delay -clock sys_clk -min {{INPUT_MIN_NS}} [get_ports i_data*]
set_input_delay -clock sys_clk -max {{INPUT_MAX_NS}} [get_ports i_valid]
set_input_delay -clock sys_clk -min {{INPUT_MIN_NS}} [get_ports i_valid]

# For DDR inputs (both edges)
# set_input_delay -clock sys_clk -max {{MAX}} -clock_fall -add_delay [get_ports i_ddr_data*]

##############################################################
# 5. Output Constraints
##############################################################
# External output delay: setup = Tsetup(ext) + Tboard, hold = Thold(ext) + Tboard
set_output_delay -clock sys_clk -max {{OUTPUT_MAX_NS}} [get_ports o_data*]
set_output_delay -clock sys_clk -min {{OUTPUT_MIN_NS}} [get_ports o_data*]
set_output_delay -clock sys_clk -max {{OUTPUT_MAX_NS}} [get_ports o_valid]
set_output_delay -clock sys_clk -min {{OUTPUT_MIN_NS}} [get_ports o_valid]

##############################################################
# 6. False Paths
##############################################################
# EVERY false_path MUST have a justification comment

# Async reset — asynchronous assertion, no timing path
# Source: RTL convention — {domain}_rst_n is async assert, sync deassert
set_false_path -from [get_ports *_rst_n]

# Static configuration registers — written only during init, never during operation
# Source: uarch/ctrl.md — config registers are quasi-static
# set_false_path -from [get_cells u_ctrl/config_reg*]

# Test/debug paths — not active during normal operation
# set_false_path -through [get_ports i_scan_*]

##############################################################
# 7. Multicycle Paths
##############################################################
# ALWAYS set both -setup and -hold for each MCP

# N-cycle pipeline stage — data valid every N clocks
# Source: uarch/{{MODULE}}.md — N-stage pipeline
# set_multicycle_path {{N}} -setup \
#   -from [get_cells u_pipe/stage1_reg*] \
#   -to   [get_cells u_pipe/stage{{N}}_reg*]
# set_multicycle_path {{N-1}} -hold \
#   -from [get_cells u_pipe/stage1_reg*] \
#   -to   [get_cells u_pipe/stage{{N}}_reg*]

# Multi-cycle computation (e.g., MAC unit takes 4 cycles)
# Source: uarch/mac_unit.md pipeline table
# set_multicycle_path 4 -setup -from [get_cells u_mac/*] -to [get_cells u_mac/o_result_reg*]
# set_multicycle_path 3 -hold  -from [get_cells u_mac/*] -to [get_cells u_mac/o_result_reg*]

##############################################################
# 8. Design Rules
##############################################################
# Max fanout — prevent excessive loading
set_max_fanout 32 [current_design]

# Max transition (slew) — technology dependent
set_max_transition 0.5 [current_design]

# Max capacitance — for output ports
# set_max_capacitance 0.5 [get_ports o_*]

# Driving cell and load for I/O ports
# set_driving_cell -lib_cell {{BUF_CELL}} [get_ports i_*]
# set_load {{LOAD_PF}} [get_ports o_*]

##############################################################
# 9. Area / Power (optional)
##############################################################
# set_max_area 0  ;# let tool minimize
# set_max_dynamic_power 0

##############################################################
# 10. Dont Touch (only with explicit user approval)
##############################################################
# set_dont_touch [get_cells u_sync_*]  ;# preserve synchronizer structure
