// sram_2p_wrapper.sv — Convention-compliant wrapper skeleton for vendor_sram_2p
// Translates vendor port naming to project conventions:
//   Vendor: CLKA/CENA/AA  →  Project: a_clk/i_cena/i_aa
//
// Generated by rtl-agent-team:rtl-ip-instantiate (gen_instantiation.py)
// Hand-tune before delivery: merge/rename clock domains, give mapped
// ports functional names, verify polarities, resolve TODO markers.

module sram_2p_wrapper #(
  // ─── Parameters (UPPER_SNAKE_CASE) ────────────────────────────────
  parameter int W = 32,   // PARAM: TODO — describe purpose (vendor: W)
  parameter int D = 256   // PARAM: TODO — describe purpose (vendor: D)
) (
  // ─── Clock / Reset (project convention) ───────────────────────────
  input  logic                 a_clk,
  input  logic                 b_clk,

  // ─── Input ports (i_ prefix) ──────────────────────────────────────
  input  logic                 i_cena,
  input  logic [$clog2(D)-1:0] i_aa,
  input  logic [W-1:0]         i_da,
  input  logic                 i_cenb,
  input  logic [$clog2(D)-1:0] i_ab,

  // ─── Output ports (o_ prefix) ─────────────────────────────────────
  output logic [W-1:0]         o_qb
);

  // ─── Vendor IP Instance ───────────────────────────────────────────
  vendor_sram_2p #(
    .W (W),
    .D (D)
  ) u_sram_2p (
    // Clock/Reset mapping
    //   Vendor  →  Project
    .CLKA   (a_clk),
    .CLKB   (b_clk),

    // Data port mapping
    .CENA   (i_cena),
    .AA     (i_aa),
    .DA     (i_da),
    .CENB   (i_cenb),
    .AB     (i_ab),
    .QB     (o_qb),

    // ─── Tie-offs (unused vendor ports) ─────────────────────────────
    .EMA    (3'b010),  // TIED: vendor-recommended margin setting
    .RET1N  (1'b1),    // TIED: retention mode not used
    .STOV   (1'b0)     // TIED: self-time override disabled
  );

  // ─── Tie-off Documentation ────────────────────────────────────────
  // | Vendor Port | Tied To | Reason                            |
  // |-------------|---------|-----------------------------------|
  // | EMA         | 3'b010  | vendor-recommended margin setting |
  // | RET1N       | 1'b1    | retention mode not used           |
  // | STOV        | 1'b0    | self-time override disabled       |

endmodule
