// {{WRAPPER_NAME}}.sv — Convention-compliant wrapper for {{IP_NAME}}
// Translates vendor port naming to project conventions:
//   Vendor: clk_i/rst_ni/data_i/data_o  →  Project: {domain}_clk/{domain}_rst_n/i_data/o_data
//
// Generated by rtl-agent-team:rtl-ip-instantiate

module {{WRAPPER_NAME}}
  // TODO: Uncomment if wrapper needs a package
  // import {{WRAPPER_NAME}}_pkg::*;
#(
  // ─── Parameters (UPPER_SNAKE_CASE) ─────────────────────────────────
  parameter int DATA_WIDTH = {{DATA_WIDTH}}
) (
  // ─── Clock / Reset (project convention) ────────────────────────────
  input  logic                  {{DOMAIN}}_clk,
  input  logic                  {{DOMAIN}}_rst_n,

  // ─── Input ports (i_ prefix) ───────────────────────────────────────
  // TODO: Map from vendor ports
  input  logic [DATA_WIDTH-1:0] i_data,
  input  logic                  i_valid,

  // ─── Output ports (o_ prefix) ──────────────────────────────────────
  output logic [DATA_WIDTH-1:0] o_data,
  output logic                  o_ready
);

  // ─── Vendor IP Instance ────────────────────────────────────────────
  {{IP_NAME}} #(
    .DATA_WIDTH (DATA_WIDTH)
  ) u_{{IP_SHORT_NAME}} (
    // Clock/Reset mapping
    //   Vendor          →  Project
    .clk_i              ({{DOMAIN}}_clk),
    .rst_ni             ({{DOMAIN}}_rst_n),

    // Data port mapping
    //   Vendor          →  Project
    .data_i             (i_data),
    .valid_i            (i_valid),
    .data_o             (o_data),
    .ready_o            (o_ready)

    // ─── Tie-offs (unused vendor ports) ──────────────────────────────
    // .scan_mode_i     (1'b0),    // Tie-off: scan not used
    // .debug_o         (/* NC */), // Tie-off: debug not connected
  );

  // ─── Tie-off Documentation ─────────────────────────────────────────
  // | Vendor Port    | Tied To | Reason                    |
  // |----------------|---------|---------------------------|
  // | scan_mode_i    | 1'b0    | No scan chain in design   |
  // | debug_o        | NC      | Debug port not needed     |

endmodule
