// sram_2p_wrapper.sv — Convention-compliant wrapper for vendor_sram_2p (256x32 two-port SRAM macro)
// Translates vendor port naming to project conventions:
//   Vendor: CLKA/CLKB/AA/DA/... → Project: sys_clk / i_wr_* / o_rd_*
//
// Generated by rtl-agent-team:rtl-ip-instantiate

module sram_2p_wrapper #(
  // ─── Parameters (UPPER_SNAKE_CASE) ─────────────────────────────────
  parameter int ADDR_WIDTH = 8,   // PARAM: word address width (256 words)
  parameter int DATA_WIDTH = 32   // PARAM: word width in bits
) (
  // ─── Clock (project convention; macro has no reset) ────────────────
  input  logic                  sys_clk,

  // ─── Write port (i_ prefix) ────────────────────────────────────────
  input  logic                  i_wr_en,
  input  logic [ADDR_WIDTH-1:0] i_wr_addr,
  input  logic [DATA_WIDTH-1:0] i_wr_data,

  // ─── Read port ─────────────────────────────────────────────────────
  input  logic                  i_rd_en,
  input  logic [ADDR_WIDTH-1:0] i_rd_addr,
  output logic [DATA_WIDTH-1:0] o_rd_data
);

  // ─── Vendor IP Instance ────────────────────────────────────────────
  // vendor_sram_2p: port A = write, port B = read; enables active-low.
  vendor_sram_2p #(
    .W (DATA_WIDTH),
    .D (2**ADDR_WIDTH)
  ) u_sram_2p (
    // Clock mapping
    //   Vendor  →  Project
    .CLKA      (sys_clk),
    .CLKB      (sys_clk),

    // Write port mapping (port A)
    .CENA      (~i_wr_en),      // vendor chip-enable is active-low
    .AA        (i_wr_addr),
    .DA        (i_wr_data),

    // Read port mapping (port B)
    .CENB      (~i_rd_en),      // vendor chip-enable is active-low
    .AB        (i_rd_addr),
    .QB        (o_rd_data),

    // ─── Tie-offs (unused vendor ports) ──────────────────────────────
    .EMA       (3'b010),        // TIED: vendor-recommended margin setting
    .RET1N     (1'b1),          // TIED: retention mode not used
    .STOV      (1'b0)           // TIED: self-time override disabled
  );

  // ─── Tie-off Documentation ─────────────────────────────────────────
  // | Vendor Port | Tied To | Reason                                  |
  // |-------------|---------|-----------------------------------------|
  // | EMA         | 3'b010  | Vendor-recommended read margin (DS §4.2)|
  // | RET1N       | 1'b1    | Retention mode not used in this design  |
  // | STOV        | 1'b0    | Self-time override disabled             |

endmodule
